# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugins:
  import-secrets:
    image: ghcr.io/loft-sh/vcluster-example-import-secrets:v1
    imagePullPolicy: IfNotPresent
