# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  pull-secret-sync:
    image: ghcr.io/loft-sh/vcluster-example-pull-sycret-sync:v1
    imagePullPolicy: IfNotPresent